CXX = g++
CXXFLAGS = -std=c++11 -Wall -Ihospital -Ipacientes -Idoctores -Icitas -Ihistorial -Ipersistencia -Iutilidades

# Archivos fuente
SRC = main.cpp \
      hospital/Hospital.cpp \
      pacientes/Paciente.cpp \
      pacientes/operacionesPacientes.cpp \
      doctores/Doctor.cpp \
      doctores/operacionesDoctores.cpp \
      citas/Cita.cpp \
      citas/operacionesCitas.cpp \
      historial/HistorialMedico.cpp \
      persistencia/GestorArchivos.cpp \
      utilidades/Validaciones.cpp

# Objetos
OBJ = $(SRC:.cpp=.o)

# Nombre del ejecutable
TARGET = tareaHospital

# Regla principal
all: $(TARGET)

$(TARGET): $(OBJ)
    $(CXX) $(CXXFLAGS) -o $@ $(OBJ)

# Regla para limpiar archivos compilados
clean:
    rm -f $(OBJ) $(TARGET)